### ISSUE TITLE
osx installation guide

### ISSUE THREAD

**Issue by ryandeussing** [redhataccess/pantheon-cmd#30]
As an OSX user
I'd like instructions on extracting/installing rpm content
So that I can give pantheon-cmd a test drive

Thanks ;)

**Comment by pwright** [comment]
On mac, my experience was:

```
$ sh make.sh 1.0
Building pantheon-cmd...
Getting HAML templates...
svn: error: The subversion command line tools are no longer provided by Xcode.
```

**Comment by pwright** [comment]
Installed svn using `brew install svn`, then I could:

```
sudo gem install asciidoctor concurrent-ruby haml tilt
sh make.sh 1.0
```

While that make fails, you can now preview a pv2 repo (I used https://github.com/redhataccess/pantheon):


1. change to the pv2 repo.
2. run the script to generate a preview:

```
python3 <this-repo-dir>/PantheonCMD/pcmd.py preview
```
