### ISSUE TITLE
package pantheon-cmd for macOS

### ISSUE THREAD

**Issue by ryandeussing** [redhataccess/pantheon-cmd#32]
Validating and previewing modular docs is a cross-platform use case, so I'd like to suggest that this tool be enhanced to function on macOS. I believe this is a two-part process:

1. Confirm that all code works cross-platform. 

For example, the following modification (the addition of an empty string parameter) allows the commands that modify the css references in the base Haml template to run successfully on OS X:

```bash
sed -i '' 's/^-\ pantheonCssPath.*/-\ pantheonCssPath\ \=\ \"resources\/rhdocs.min.css\"/' PantheonCMD/haml/document.html.haml
sed -i '' 's/href\=\"https\:\/\/static\.redhat\.com\/libs\/redhat\/redhat-font\/2\/webfonts\/red-hat-font\.css/href\=\"resources\/red-hat-font.css/' PantheonCMD/haml/document.html.haml
```

With that change, the `sh make.sh` command works on macOS, as long as [rpm](https://formulae.brew.sh/formula/rpm) is properly installed. But the make build only builds rpms.

2. Create a [Homebrew](https://brew.sh/) formula (and perhaps a [Tap](https://github.com/atlassian/homebrew-tap) where it and others can live) to package up pantheon-cmd for macOS users.

I'm not the person to accomplish step two, but I'm hopeful that person exists within CCS.

**Comment by ryandeussing** [comment]
@pwright maybe you're interested? ☝️

**Comment by ryandeussing** [comment]
And since I failed to say so above: I think this is a super initiative! Local validation, previewing, and pre-flighting of docs is a step in the right direction methinks!

**Comment by pwright** [comment]
@ryandeussing As a first step, perhaps we should document how to use this super tool on macOS first? 
@adahms Are there any plans for documenting pantheon-cmd on a website? would the project be open to macOS doc contributions?

**Comment by ryandeussing** [comment]
With a Homebrew formula, you'd get `pcmd` at the command line, so the usage should be about the same, if not identical, and I think this repo can serve as docs.

**Comment by adahms** [comment]
Hey @ryandeussing @pwright - thanks for raising this issue, and for the discussion!

We are absolutely open to macOS contributions, and I put together a rudimentary set of instructions for getting things up and running here - 

https://github.com/redhataccess/pantheon-cmd/blob/Issue_32/README.md

I'd love to get your take on these, otherwise we can investigate a proper Homebrew package, perhaps.

Preferences?

**Comment by adahms** [comment]
Hey @ryandeussing @pwright - since things have gone quiet for a while, I've merged and closed this one for now so that we have some instructions in place.

That said, I recognize there's plenty of room to improve on the current steps, and will investigate a more refined option as time allows.
