### ISSUE TITLE
The 'generate' action only runs if a pantheon2.yml file already exists

### ISSUE THREAD

**Issue by adahms** [redhataccess/pantheon-cmd#34]
Today, PCMD always searches for a pantheon2.yml file before running actions. If no pantheon2.yml file is present, this means the tool exists before it reaches the 'generate' action.

We should restructure the actions so there's a set that don't need a pantheon2.yml file, then check if the file is there, then our remaining actions that do need it.

**Comment by Levi-Leah** [comment]
I’ll fix that ASAP

**Comment by Levi-Leah** [comment]
This also affects the PR validation

**Comment by Levi-Leah** [comment]
addressed in https://github.com/redhataccess/pantheon-cmd/pull/37
